### ISSUE TITLE
[Bug] Metadata leakage on pulling files from api

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-archiveinterface#81]
### Pacifica Archive Interface version
v0.2.0

### Scenario:
Get data directly from Archiveinterface API

### Steps to Reproduce:
```
curl 127.0.0.1:8080/###### -o test.tar
tar -xvf test.tar
cd test/
less metadata.txt
```

### Expected Result:
Only metadata relating to the transaction or data itself.

### Actual Result:
Lots more metadata than is expected.

**Comment by dmlb2000** [comment]
So this isn't a bug in the archive interface, the metadata got stored in the file and sent to the archive interface. The archive interface sent you the data since you requested it.

This should be filed against the CLI or uploader library. The metadata file does contain query results from the perspective of the person who uploaded the data not the data consumer. So, the query results from the uploader should be used through the process of uploading but dropped before shipped to the ingest process.
